const USER_ACTION_TYPES = {
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS:'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE:'FETCH_USER_FAILURE',
    SIGNOUT_USER_START:'SIGNOUT_USER_START',
    SIGNOUT_USER_SUCCESS:'SIGNOUT_USER_SUCCESS',
    SIGNOUT_USER_FAILURE:'SIGNOUT_USER_FAILURE'
}
export default USER_ACTION_TYPES
